### ISSUE TITLE
error when using gateway template - route --verbose

### ISSUE THREAD

**Issue by poblin-orange** [cf-platform-eng/networking-boshrelease#1]
Tried to use the gateway template to fix a specific gateway on my bosh vms, stemcell 3033.

I get the following error in /var/vcap/sys/log/monit/gateway.err.log :

route: unrecognized option '--verbose'
BusyBox v1.23.1 (2015-06-10 01:10:20 UTC) multi-call binary.

Usage: route [{add|del|delete}]

Edit kernel routing tables

        -n      Don't resolve names
        -e      Display other/more information
        -A inet{6}      Select address family

route: unrecognized option '--verbose'
BusyBox v1.23.1 (2015-06-10 01:10:20 UTC) multi-call binary.

Usage: route [{add|del|delete}]

Removing the --verbose flag in the jobs/gateway/gateway.ctl.erb seem to fix the issue (default gateway set)

**Comment by frodenas** [comment]
@poblin-orange What IaaS are you using? On an AWS stemcell 3033 the verbose option is supported:

```
root@885cf44e-8765-4213-9c72-c5d999d06494:~# route --verbose
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         ip-10-0-16-1.ec 0.0.0.0         UG    0      0        0 eth0
10.0.16.0       *               255.255.240.0   U     0      0        0 eth0
root@885cf44e-8765-4213-9c72-c5d999d06494:~# route --help
Usage: route [-nNvee] [-FC] [<AF>]           List kernel routing tables
       route [-v] [-FC] {add|del|flush} ...  Modify routing table for AF.

       route {-h|--help} [<AF>]              Detailed usage syntax for specified AF.
       route {-V|--version}                  Display version/author and exit.

        -v, --verbose            be verbose
        -n, --numeric            don't resolve names
        -e, --extend             display other/more information
        -F, --fib                display Forwarding Information Base (default)
        -C, --cache              display routing cache instead of FIB

  <AF>=Use '-A <af>' or '--<af>'; default: inet
  List of possible address families (which support routing):
    inet (DARPA Internet) inet6 (IPv6) ax25 (AMPR AX.25)
    netrom (AMPR NET/ROM) ipx (Novell IPX) ddp (Appletalk DDP)
    x25 (CCITT X.25)
```

Seems also weird that you got a `BusyBox v1.23.1` message, this doesn't seem to be a bosh stemcell.

**Comment by poblin-orange** [comment]
@frodenas ur correct, route --verbose is ok when launching with bosh ssh (btw, my stemcell is a openstack-kvm stemcell, converted in vhd format for my cloudstack cpi dev).

In fact, i collocate the networking bosh release with concourse-ci, wich happens to package /sbin/route ...

Guess its the root cause.

root@50290ca6-c76e-4409-8c63-98f0afa38840:/# find . -name "route"
./sbin/route                                                     
./var/vcap/data/packages/semver_resource/17e0e0cf683b9b372bc5cd5e2b5137a0ac57aa1c.1-76894630ad79b3df68b7dfafe98745a380bfef91/sbin/route
./var/vcap/data/packages/docker_image_resource/811acf49eb583574292fe1d6c32bbeea6ef99288.1-afa5d05a404eca5ca5067e43a221f9943eb740de/sbin/route
./var/vcap/data/packages/bosh_deployment_resource/1a43050db7207b5f089e65df2b2679579058738a.1-7c880bcaf06718d50f5be74927f5cef33a6fc698/sbin/route
./var/vcap/data/packages/time_resource/06194e0f4e3015470011490b1d0f7bcd37a857f4.1-e6af917d2737b55769c8eb91504bb8f2c8a46d11/sbin/route           
./var/vcap/data/packages/bosh_io_stemcell_resource/b6017e6fcfb3a5556de6e44e87395e2052e9d859.1-2ae90dc5b8191627a6b52482d700f639472b4127/sbin/route
./var/vcap/data/packages/github_release_resource/3d6932a628b87ad3fe2645ad34c14e3debc146d2.1-68bcc45da16553c61dd40b4fe25a52be76d15809/sbin/route  
./var/vcap/data/packages/s3_resource/4438516f0ffc4791389710a9132074771f617495.1-a3d2dd0c74c30e17bbb2a2ed391c6463b7d74b33/sbin/route              
./var/vcap/data/packages/git_resource/0f0ac4080a8986c9e66ba3b709400e821ead31fd.1-0ada9c2355ed2091609f332f9c0786ea7c37fa5e/sbin/route             
./var/vcap/data/packages/vagrant_cloud_resource/34b4d5a6ff59561df2d45045098f4106670829d9.1-214b82977ce2fab26f942ad510dea16c3ecb2ea6/sbin/route   
./var/vcap/data/packages/pool_resource/4a63fd6bdf121d860327ee3ac3b068eb4594a519.1-6d570781dd9f97d37a85f4ad0c1bdca59274e5b2/sbin/route            
./var/vcap/data/packages/cf_resource/2e6ecdc1d6f1990a9b696934a8bf1c6bb25fbc63.1-2991f3ea89984bc3403f82042c5949dde36623b9/sbin/route              
./var/vcap/data/packages/bosh_io_release_resource/39cc3331481e6ca18ca86874256c7980505bb97f.1-439b16c1aa10e0011df28b618278676eb91632ea/sbin/route 
./var/vcap/data/packages/busybox/1593c41beb57c12d7f2b82dff61b47d4d119913d.1-1382c6321b7db1a981e6274e65b93fb67594acbf/sbin/route                  
./var/vcap/data/packages/archive_resource/34b312db22a31df42d3a74cdb7e2ec53ba85c891.1-f51e8dc1d6ebfa970216dfd75c7599ab2a29ccd0/sbin/route         
./var/vcap/data/packages/tracker_resource/3e35fbc19901fa659c61bc0d8f5fdeaf8b99f4b2.1-d05da72b80922bf4267091ee3ca8d472b6fd5679/sbin/route

**Comment by frodenas** [comment]
That's really annoying. Wonder why they are packaging a full busybox image in the release packages. I'll prefix the `route` command to avoid conflicts.

**Comment by poblin-orange** [comment]
thks @frodenas. I will raise an issue on concourse side, quite strange ...

**Comment by frodenas** [comment]
@poblin-orange Just pushed a [v2 release](http://bosh.io/releases/github.com/cf-platform-eng/networking-boshrelease) with the `route` command prefixed. Give it a try, it should work now.

**Comment by vito** [comment]
That must be a red herring. Our packages are just rootfses on disk, nothing should be creeping into `/var/vcap/packages/*` arbitrarily. Nothing in Concourse is going to modify `/sbin/route` (or anything else that's a global system resource).

**Comment by frodenas** [comment]
@vito This was due to a helper script [adding all package's *bin directories](https://github.com/cf-platform-eng/networking-boshrelease/blob/master/src/bosh-helpers/ctl_setup.sh#L34) to the path (we can argue if this is or is not a good approach on a separate thread). Once the `route` command has been prefixed with the correct location, the issue has been solved.

**Comment by poblin-orange** [comment]
v2 fixed my issues. Thks guys, sorry bout the noise ;-)
