### ISSUE TITLE
gateway job's `packages` should be an array

### ISSUE THREAD

**Issue by cppforlife** [cf-platform-eng/networking-boshrelease#4]
...bosh.io cannot build v3 final release.

https://github.com/cf-platform-eng/networking-boshrelease/blob/master/jobs/gateway/spec#L4

**Comment by frodenas** [comment]
Fixed at https://github.com/cf-platform-eng/networking-boshrelease/commit/803b2182ae08ce67a70a06a6a9fea4d176149d5f, thanks @cppforlife!
