### ISSUE TITLE
yank networking v3 (releases/networking/networking-3.yml)

### ISSUE THREAD

**Issue by cppforlife** [cf-platform-eng/networking-boshrelease#5]
Can you yank networking v3 so that bosh.io does not try to rebuild it?

**Comment by frodenas** [comment]
Is bosh.io looking only at the gh releases? or does it looks at the bosh releases directory? The latter will require do revert the v3 commit, is this what you are asking for?

**Comment by frodenas** [comment]
Never mind. Reverted v3 at https://github.com/cf-platform-eng/networking-boshrelease/commit/788f2ed59f9812f2eed4a93adcc3f1b9909141ce.
