### ISSUE TITLE
Add an example for networking.routes property

### ISSUE THREAD

**Issue by cppforlife** [cf-platform-eng/networking-boshrelease#6]
Would be nice to see a full example with all sub keys for `networking.routes` key.

UAA release does something similar: https://github.com/cloudfoundry/uaa-release/blob/bd0a2384839f2958941dee36ef2f99b92ea4788b/jobs/uaa/spec#L459. Once example key is added bosh.io will display it.

**Comment by frodenas** [comment]
Example added here: https://github.com/cf-platform-eng/networking-boshrelease/commit/411b8387ea8e8ca7e5df433f067780d10234a67e.
